name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "19.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77dbfe8f9ecb0d1f2f625ce38621b6662dc6805396986a8a67a38723eda7a94e"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
