name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "19.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8ff084852af244648b4919a7521b7590b1a9819a34329123e4ff6fa35a5563"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
