name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "19.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a7242a78cd6cd65fbd0d41566134bab4d9a07cf61bb6330c82126e390a5d8a8"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
