name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "20.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ea88481d23645548edbb5d09adb3263fb877f292a2aea53caccbc3f7f322886"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
