name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "19.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eba3dab77c7fb61796592d2aabcc55d13a475d865cc8ca42f8614712628772e"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
