name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "19.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9de3949ab04cdca0156f56a6a07a26fca3855469dadf9d19318d9348085407ec"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
