name = "DSRVMC Vanilla Modpack"
author = "DSRKafuU"
version = "20.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b5d16ab560bfddb032db48d0fbfa22a5ac234aa217fb295b0eccd083e4c90b7"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
